author: Toomas Vahter
author_url: https://www.augmentedcode.io
github_url: https://github.com/laevandus/IndexedDataStore
output: Docs
swift_build_tool: xcodebuild
build_tool_arguments:
  - -scheme
  - IndexedDataStore
  - -sdk
  - iphoneos
  - -destination,platform=iOS Simulator,OS=latest,name=iPhone 11 Pro
