name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: brew bundle
    - name: Lint
      run: swiftlint
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
